#!/usr/bin/env bash
set -euo pipefail

SERVICE_NAME="${1:-}"
if [[ -z "$SERVICE_NAME" ]]; then
  echo "Usage: $0 <service-name>" >&2
  exit 2
fi

TEMPLATE="src/grafana/provisioning/dashboards/demo/apm-dashboard.json"
OUT_DIR="src/grafana/provisioning/dashboards/demo"
OUT_FILE="${OUT_DIR}/${SERVICE_NAME}-apm-dashboard.json"

if [[ ! -f "$TEMPLATE" ]]; then
  echo "Template not found: ${TEMPLATE}" >&2
  exit 1
fi

mkdir -p "$OUT_DIR"

# Generate a deterministic-ish Grafana dashboard UID (must be unique per dashboard).
DASH_UID="${SERVICE_NAME}-apm"

jq \
  --arg service_name "$SERVICE_NAME" \
  --arg title "${SERVICE_NAME} - APM Dashboard" \
  --arg uid "$DASH_UID" \
  '
    .title = $title
    | .uid = $uid
    | .description = ("APM dashboard for " + $service_name + " — auto-generated by IncidentFox Telemetry Agent. Monitors request rate, error rate, and latency (P95/P99).")
    | (
        .templating.list
        | map(
            if .name == "service_name" then
              .current.text = $service_name
              | .current.value = $service_name
            else
              .
            end
          )
      ) as $templating
    | .templating.list = $templating
  ' \
  "$TEMPLATE" > "$OUT_FILE"

echo "Wrote ${OUT_FILE}"

