#!/usr/bin/env bash
set -euo pipefail

SERVICE_NAME="${1:-}"
if [[ -z "$SERVICE_NAME" ]]; then
  echo "Usage: $0 <service-name>" >&2
  exit 2
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TEMPLATE="${SCRIPT_DIR}/templates/service-apm-dashboard.json"
OUT_DIR="src/grafana/provisioning/dashboards/demo"
OUT_FILE="${OUT_DIR}/${SERVICE_NAME}-apm-dashboard.json"

if [[ ! -f "$TEMPLATE" ]]; then
  echo "Template not found: ${TEMPLATE}" >&2
  exit 1
fi

mkdir -p "$OUT_DIR"

DASH_UID="${SERVICE_NAME}-apm"
DASH_TITLE="${SERVICE_NAME} - APM Dashboard"
DESCRIPTION="APM dashboard for ${SERVICE_NAME} - auto-generated by IncidentFox Telemetry Agent. Monitors request rate, error rate, latency (P95/P99), and service-specific business metrics."

# Replace placeholders in the template.
jq \
  --arg uid "$DASH_UID" \
  --arg title "$DASH_TITLE" \
  --arg desc "$DESCRIPTION" \
  '.uid = $uid | .title = $title | .description = $desc' \
  "$TEMPLATE" \
  | sed "s/__SERVICE_NAME__/${SERVICE_NAME}/g" \
  | sed "s/__UID__/${DASH_UID}/g" \
  | sed "s/__TITLE__/${DASH_TITLE}/g" \
  > "$OUT_FILE"

echo "Generated ${OUT_FILE}"
